version: "3"
services:
  mysql:
    container_name: mysql_incidence_manager
    image: mysql:8
    platform: linux/amd64
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS incidence_manager' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    command: ["--default-authentication-plugin=mysql_native_password"]
  axonserver:
    image: axoniq/axonserver
    container_name: axonserver
    ports:
      - 8024:8024
      - 8124:8124
    depends_on:
      - mysql
  java:
    container_name: java-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8030:8080"
    volumes:
      - .:/app:delegated
    tty: true
    depends_on:
       - mysql
       - axonserver
